name: pvforecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - pytorch
  - torchvision
  - torchaudio
  - torchmetrics
  - xgboost
  - lightgbm
  - optuna
  - pvlib
  - xarray
  - netCDF4
  - shap
  - streamlit
  - altair
  - pydeck
  - tqdm
  - joblib
  - requests
  - pyarrow
  - python-dotenv
  - pillow
  - opencv
  - scikit-image
  - jupyterlab
  - pytorch-lightning
  - pytorch-forecasting
  - gymnasium
  - stable-baselines3
  - torchrl
  - pytorch-optimizer
